=== disbeat/camera_info/IS-Projecto4/xml/camera_list.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="camera">
    <xs:complexType>
      <xs:all>
        <xs:element ref="name" />
        <xs:element ref="description" />
        <xs:element ref="summary" />
        <xs:element ref="effectivePixels" />
        <xs:element ref="shutterTime" />
        <xs:element ref="links" />
        <xs:element ref="releasedDate" />
        <xs:element ref="resolutions" />
        <xs:element ref="imageRatios" />
        <xs:element ref="ISOratings" />
        <xs:element ref="sensorSize" />
      </xs:all>
      <xs:attribute name="id" type="xs:decimal" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="cameras">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="camera" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="brand" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="description" type="xs:string" />

  <xs:element name="summary" type="xs:string" />

  <xs:element name="effectivePixels" type="xs:string" />

  <xs:element name="imageRatio">
    <xs:complexType>
      <xs:attribute name="height" use="required" type="xs:integer" />
      <xs:attribute name="width" use="required" type="xs:integer" />
    </xs:complexType>
  </xs:element>

  <xs:element name="imageRatios">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="imageRatio" maxOccurs="unbounded" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="inDepthReview" type="xs:string" />

  <xs:element name="ISOrating" type="xs:string" />

  <xs:element name="ISOratings">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ISOrating" maxOccurs="unbounded" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="links">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="inDepthReview" />
        <xs:element ref="picture" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="lowResolutions">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="resolution" maxOccurs="unbounded" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="maxResolution">
    <xs:complexType>
      <xs:attribute name="height" use="required" type="xs:integer" />
      <xs:attribute name="width" use="required" type="xs:integer" />
    </xs:complexType>
  </xs:element>

  <xs:element name="name" type="xs:string" />

  <xs:element name="picture" type="xs:string" />

  <xs:element name="releasedDate" type="xs:date" />

  <xs:element name="resolution">
    <xs:complexType>
      <xs:attribute name="height" use="required" type="xs:integer" />
      <xs:attribute name="width" use="required" type="xs:integer" />
    </xs:complexType>
  </xs:element>

  <xs:element name="resolutions">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="maxResolution" />
        <xs:element ref="lowResolutions" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="sensorSize">
    <xs:complexType>
      <xs:attribute name="height" use="required" type="xs:decimal" />
      <xs:attribute name="width" use="required" type="xs:decimal" />
    </xs:complexType>
  </xs:element>

  <xs:element name="shutterTime">
    <xs:complexType>
      <xs:attribute name="max" type="xs:string" use="required" />
      <xs:attribute name="min" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

</xs:schema>

=== disbeat/camera_info/IS-Projecto4/xml/agfa.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="CameraListBeautifier.xsl"?>
<cameras xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="camera_list.xsd" brand="agfa">
  <camera id="0">
    <name>AgfaPhoto DC-600uw</name>
    <description>6.0 million effective pixels;  MP/cm^2 pixel density;</description>
    <summary />
    <effectivePixels>6.0 million</effectivePixels>
    <shutterTime min="8 sec" max="1/1000 sec" />
    <links>
      <inDepthReview />
      <picture>http://a.img-dpreview.com/reviews/images/agfa_dc600uw.gif</picture>
    </links>
    <releasedDate>2009-06-29</releasedDate>
    <resolutions>
      <maxResolution width="3680" height="2760" />
      <lowResolutions>
        <resolution width="2816" height="2112" />
        <resolution width="2048" height="1536" />
        <resolution width="640" height="480" />
      </lowResolutions>
    </resolutions>
    <imageRatios>
      <imageRatio width="4" height="3" />
    </imageRatios>
    <ISOratings>
      <ISOrating>Auto</ISOrating>
      <ISOrating>100</ISOrating>
      <ISOrating>200</ISOrating>
      <ISOrating>400</ISOrating>
      <ISOrating>800</ISOrating>
      <ISOrating>1600</ISOrating>
      <ISOrating />
    </ISOratings>
    <sensorSize width="640.0" height="480.0" />
  </camera>
</cameras>

=== disbeat/camera_info/IS-Projecto4/xml/epson.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="CameraListBeautifier.xsl"?>
<cameras xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="camera_list.xsd" brand="epson">
  <camera id="0">
    <name>Epson R-D1x</name>
    <description>6.0 million effective pixels; 1.6 MP/cm^2 pixel density;</description>
    <summary>Latest version of the world's first (and until recently the only) digital rangefinder, originally launched in 2004 and amazingly still in production (albeit only for sale in Japan). The new R-D1x model maintains most of the features of the previous camera including a 6Mp APS-C sensor, but adds a larger 2.5" LCD screen, support for the higher-capacity SD-HC card format and a removable handgrip. Based around a Cosina rangefinder camera with Leica M mount, the RD-1 combines classic camera styling with digital capture - and it still costs a lot less than the Leica M8.</summary>
    <effectivePixels>6.0 million</effectivePixels>
    <shutterTime min="1 sec" max="1/2000 sec" />
    <links>
      <inDepthReview />
      <picture>http://a.img-dpreview.com/reviews/images/epson_rd1x.gif</picture>
    </links>
    <releasedDate>2009-02-27</releasedDate>
    <resolutions>
      <maxResolution width="3008" height="2000" />
      <lowResolutions>
        <resolution width="2240" height="1488" />
      </lowResolutions>
    </resolutions>
    <imageRatios>
      <imageRatio width="3" height="2" />
    </imageRatios>
    <ISOratings>
      <ISOrating>200</ISOrating>
      <ISOrating>400</ISOrating>
      <ISOrating>800</ISOrating>
      <ISOrating>1600</ISOrating>
      <ISOrating />
    </ISOratings>
    <sensorSize width="23.7" height="15.6" />
  </camera>
</cameras>

=== disbeat/camera_info/IS-Projecto4/xml/hp.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="CameraListBeautifier.xsl"?>
<cameras xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="camera_list.xsd" brand="hp">
  <camera id="0">
    <name>HP Photosmart R937</name>
    <description>8.2 million effective pixels; 33 MP/cm^2 pixel density; 39 mm - 118 mm (3x) zoom lens;</description>
    <summary />
    <effectivePixels>8.2 million</effectivePixels>
    <shutterTime min="10 sec" max="1/2000 sec" />
    <links>
      <inDepthReview />
      <picture>http://a.img-dpreview.com/reviews/images/hp_r937.gif</picture>
    </links>
    <releasedDate>2007-06-22</releasedDate>
    <resolutions>
      <maxResolution width="3298" height="2474" />
      <lowResolutions />
    </resolutions>
    <imageRatios>
      <imageRatio width="4" height="3" />
    </imageRatios>
    <ISOratings>
      <ISOrating>Auto</ISOrating>
      <ISOrating>50</ISOrating>
      <ISOrating>100</ISOrating>
      <ISOrating>200</ISOrating>
      <ISOrating>400</ISOrating>
      <ISOrating>800</ISOrating>
      <ISOrating>1600</ISOrating>
      <ISOrating />
    </ISOratings>
    <sensorSize width="5.75" height="4.31" />
  </camera>
  <camera id="1">
    <name>HP Photosmart R742</name>
    <description>7.0 million effective pixels; 28 MP/cm^2 pixel density; 36 mm - 108 mm (3x) zoom lens;</description>
    <summary />
    <effectivePixels>7.0 million</effectivePixels>
    <shutterTime min="2 sec" max="1/2000 sec" />
    <links>
      <inDepthReview />
      <picture>http://a.img-dpreview.com/reviews/images/hp_r742.gif</picture>
    </links>
    <releasedDate>2007-06-22</releasedDate>
    <resolutions>
      <maxResolution width="3096" height="3228" />
      <lowResolutions />
    </resolutions>
    <imageRatios>
      <imageRatio width="4" height="3" />
    </imageRatios>
    <ISOratings>
      <ISOrating>Auto</ISOrating>
      <ISOrating>100</ISOrating>
      <ISOrating>200</ISOrating>
      <ISOrating>400</ISOrating>
      <ISOrating />
    </ISOratings>
    <sensorSize width="5.75" height="4.31" />
  </camera>
  <camera id="2">
    <name>HP Photosmart Mz67</name>
    <description>8.0 million effective pixels; 21 MP/cm^2 pixel density; 35 mm - 210 mm (6x) zoom lens;</description>
    <summary />
    <effectivePixels>8.0 million</effectivePixels>
    <shutterTime min="2 sec" max="1/1000 sec" />
    <links>
      <inDepthReview />
      <picture>http://a.img-dpreview.com/reviews/images/hp_mz67.gif</picture>
    </links>
    <releasedDate>2007-06-22</releasedDate>
    <resolutions>
      <maxResolution width="3264" height="2448" />
      <lowResolutions />
    </resolutions>
    <imageRatios>
      <imageRatio width="4" height="3" />
    </imageRatios>
    <ISOratings>
      <ISOrating>Auto</ISOrating>
      <ISOrating>100</ISOrating>
      <ISOrating>200</ISOrating>
      <ISOrating>400</ISOrating>
      <ISOrating>800</ISOrating>
      <ISOrating />
    </ISOratings>
    <sensorSize width="7.18" height="5.32" />
  </camera>
  <camera id="3">
    <name>HP Photosmart E337</name>
    <description>5.1 million effective pixels; 21 MP/cm^2 pixel density; 36 mm § lens;</description>
    <summary />
    <effectivePixels>5.1 million</effectivePixels>
    <shutterTime min="2 sec" max="1/2000 sec" />
    <links>
      <inDepthReview />
      <picture>http://a.img-dpreview.com/reviews/images/hp_e337.gif</picture>
    </links>
    <releasedDate>2007-06-22</releasedDate>
    <resolutions>
      <maxResolution width="2576" height="1920" />
      <lowResolutions />
    </resolutions>
    <imageRatios>
      <imageRatio width="4" height="3" />
    </imageRatios>
    <ISOratings>
      <ISOrating>Auto</ISOrating>
      <ISOrating>60</ISOrating>
      <ISOrating>100</ISOrating>
      <ISOrating>200</ISOrating>
      <ISOrating>400</ISOrating>
      <ISOrating />
    </ISOratings>
    <sensorSize width="5.75" height="4.31" />
  </camera>
  <camera id="4">
    <name>HP Photosmart R837</name>
    <description>7.2 million effective pixels; 29 MP/cm^2 pixel density; 39 mm - 118 mm (3x) zoom lens;</description>
    <summary />
    <effectivePixels>7.2 million</effectivePixels>
    <shutterTime min="10 sec" max="1/2000 sec" />
    <links>
      <inDepthReview />
      <picture>http://a.img-dpreview.com/reviews/images/hp_r837.gif</picture>
    </links>
    <releasedDate>2007-03-08</releasedDate>
    <resolutions>
      <maxResolution width="3112" height="2328" />
      <lowResolutions />
    </resolutions>
    <imageRatios>
      <imageRatio width="4" height="3" />
    </imageRatios>
    <ISOratings>
      <ISOrating>Auto</ISOrating>
      <ISOrating>50</ISOrating>
      <ISOrating>100</ISOrating>
      <ISOrating>200</ISOrating>
      <ISOrating>400</ISOrating>
      <ISOrating />
    </ISOratings>
    <sensorSize width="5.75" height="4.31" />
  </camera>
  <camera id="5">
    <name>HP Photosmart M437</name>
    <description>5.0 million effective pixels; 20 MP/cm^2 pixel density; 38 mm - 114 mm (3x) zoom lens;</description>
    <summary />
    <effectivePixels>5.0 million</effectivePixels>
    <shutterTime min="1 sec" max="1/1000 sec" />
    <links>
      <inDepthReview />
      <picture>http://a.img-dpreview.com/reviews/images/hp_m437.gif</picture>
    </links>
    <releasedDate>2007-03-08</releasedDate>
    <resolutions>
      <maxResolution width="2576" height="1920" />
      <lowResolutions />
    </resolutions>
    <imageRatios>
      <imageRatio width="4" height="3" />
    </imageRatios>
    <ISOratings>
      <ISOrating>Auto</ISOrating>
      <ISOrating>100</ISOrating>
      <ISOrating>200</ISOrating>
      <ISOrating>400</ISOrating>
      <ISOrating>800</ISOrating>
      <ISOrating />
    </ISOratings>
    <sensorSize width="5.75" height="4.31" />
  </camera>
  <camera id="6">
    <name>HP Photosmart M537</name>
    <description>6.1 million effective pixels; 25 MP/cm^2 pixel density; 38 mm - 114 mm (3x) zoom lens;</description>
    <summary />
    <effectivePixels>6.1 million</effectivePixels>
    <shutterTime min="1 sec" max="1/1000 sec" />
    <links>
      <inDepthReview />
      <picture>http://a.img-dpreview.com/reviews/images/hp_m537.gif</picture>
    </links>
    <releasedDate>2007-03-08</releasedDate>
    <resolutions>
      <maxResolution width="2848" height="2128" />
      <lowResolutions />
    </resolutions>
    <imageRatios>
      <imageRatio width="4" height="3" />
    </imageRatios>
    <ISOratings>
      <ISOrating>Auto</ISOrating>
      <ISOrating>100</ISOrating>
      <ISOrating>200</ISOrating>
      <ISOrating>400</ISOrating>
      <ISOrating>800</ISOrating>
      <ISOrating />
    </ISOratings>
    <sensorSize width="5.75" height="4.31" />
  </camera>
</cameras>

=== disbeat/camera_info/IS-Projecto4/xml/sigma.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="CameraListBeautifier.xsl"?>
<cameras xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="camera_list.xsd" brand="sigma">
  <camera id="0">
    <name>Sigma DP1s</name>
    <description>4.8 million effective pixels; 1.6 MP/cm^2 pixel density; 28 mm § lens;</description>
    <summary />
    <effectivePixels>4.8 million</effectivePixels>
    <shutterTime min="30 sec" max="1/4000 sec" />
    <links>
      <inDepthReview />
      <picture>http://a.img-dpreview.com/reviews/images/sigma_dp1s.gif</picture>
    </links>
    <releasedDate>2009-10-02</releasedDate>
    <resolutions>
      <maxResolution width="2640" height="1760" />
      <lowResolutions>
        <resolution width="1776" height="1184" />
        <resolution width="1296" height="864" />
      </lowResolutions>
    </resolutions>
    <imageRatios>
      <imageRatio width="3" height="2" />
    </imageRatios>
    <ISOratings>
      <ISOrating>100</ISOrating>
      <ISOrating>200</ISOrating>
      <ISOrating>400</ISOrating>
      <ISOrating>800</ISOrating>
      <ISOrating />
    </ISOratings>
    <sensorSize width="20.7" height="13.8" />
  </camera>
  <camera id="1">
    <name>Sigma SD15</name>
    <description>4.6 million effective pixels; 1.6 MP/cm^2 pixel density;</description>
    <summary />
    <effectivePixels>4.6 million</effectivePixels>
    <shutterTime min="30 sec" max="1/4000 sec" />
    <links>
      <inDepthReview />
      <picture>http://a.img-dpreview.com/reviews/images/sigma_sd15.gif</picture>
    </links>
    <releasedDate>2008-09-23</releasedDate>
    <resolutions>
      <maxResolution width="2640" height="1760" />
      <lowResolutions>
        <resolution width="1776" height="1184" />
        <resolution width="1296" height="864" />
      </lowResolutions>
    </resolutions>
    <imageRatios>
      <imageRatio width="3" height="2" />
    </imageRatios>
    <ISOratings>
      <ISOrating>100</ISOrating>
      <ISOrating>200</ISOrating>
      <ISOrating>400</ISOrating>
      <ISOrating>800</ISOrating>
      <ISOrating>1600 (extended mode)</ISOrating>
      <ISOrating />
    </ISOratings>
    <sensorSize width="20.7" height="13.8" />
  </camera>
  <camera id="2">
    <name>Sigma DP2</name>
    <description>4.6 million effective pixels; 1.6 MP/cm^2 pixel density; 41 mm § lens;</description>
    <summary>The DP2 is Sigma's second camera to feature a large, DSLR-sized, sensor in a compact body. It offers a 41mm equivalent fixed focal-length lens with a relatively fast maximum aperture of F2.8. It also features Sigma's Foveon sensor that records red, green and blue wavelengths of light at each of its photosites (as opposed to conventional, 'Bayer' designs that record either red,&amp;nbsp; or green, or blue at each point). The camera is aimed at keen enthusaist photographers and offers a great deal of manual control and no automated scene modes.</summary>
    <effectivePixels>4.6 million</effectivePixels>
    <shutterTime min="15 sec" max="1/2000 sec" />
    <links>
      <inDepthReview>http://www.dpreview.com/reviews/sigmadp2/</inDepthReview>
      <picture>http://a.img-dpreview.com/reviews/images/sigma_dp2.gif</picture>
    </links>
    <releasedDate>2008-09-23</releasedDate>
    <resolutions>
      <maxResolution width="2640" height="1760" />
      <lowResolutions>
        <resolution width="2640" height="1485" />
        <resolution width="1872" height="1248" />
        <resolution width="1312" height="880" />
      </lowResolutions>
    </resolutions>
    <imageRatios>
      <imageRatio width="3" height="2" />
      <imageRatio width="16" height="9" />
    </imageRatios>
    <ISOratings>
      <ISOrating>100</ISOrating>
      <ISOrating>200</ISOrating>
      <ISOrating>400</ISOrating>
      <ISOrating>800 (1600 and 3200 in RAW)</ISOrating>
      <ISOrating />
    </ISOratings>
    <sensorSize width="20.7" height="13.8" />
  </camera>
  <camera id="3">
    <name>Sigma DP1</name>
    <description>4.8 million effective pixels; 1.6 MP/cm^2 pixel density; 28 mm § lens;</description>
    <summary>The DP1 uses the same Foveon X3 sensor as Sigma's SD14 DSLR and that makes it the first compact camera ever to be made with an SLR-sized sensor (it's around the same size as the Four-Thirds format). But it's not only the sensor that differentiates the new Sigma from the scores of compact cameras on the market today. With its no-nonsense feature set and 28mm (35mm equiv.) prime lens the DP1 is a million miles away from the superzooms, smile modes and face detection functions that are nowadays standard on so many compact digital cameras. Image quality is amazing for a compact, and if you can live with the slow performance, limited feature set and idiosynchratic operation it's the nearest thing yet to a pocketable SLR alternative. (April 2009)</summary>
    <effectivePixels>4.8 million</effectivePixels>
    <shutterTime min="30 sec" max="1/4000 sec" />
    <links>
      <inDepthReview>http://www.dpreview.com/reviews/sigmadp1/</inDepthReview>
      <picture>http://a.img-dpreview.com/reviews/images/sigma_dp1.gif</picture>
    </links>
    <releasedDate>2006-09-26</releasedDate>
    <resolutions>
      <maxResolution width="2640" height="1760" />
      <lowResolutions>
        <resolution width="1776" height="1184" />
        <resolution width="1296" height="864" />
      </lowResolutions>
    </resolutions>
    <imageRatios>
      <imageRatio width="3" height="2" />
    </imageRatios>
    <ISOratings>
      <ISOrating>100</ISOrating>
      <ISOrating>200</ISOrating>
      <ISOrating>400</ISOrating>
      <ISOrating>800</ISOrating>
      <ISOrating />
    </ISOratings>
    <sensorSize width="20.7" height="13.8" />
  </camera>
  <camera id="4">
    <name>Sigma SD14</name>
    <description>4.6 million effective pixels; 1.6 MP/cm^2 pixel density;</description>
    <summary />
    <effectivePixels>4.6 million</effectivePixels>
    <shutterTime min="30 sec" max="1/4000 sec" />
    <links>
      <inDepthReview />
      <picture>http://a.img-dpreview.com/reviews/images/sigma_sd14.gif</picture>
    </links>
    <releasedDate>2006-09-26</releasedDate>
    <resolutions>
      <maxResolution width="2640" height="1760" />
      <lowResolutions>
        <resolution width="1776" height="1184" />
        <resolution width="1296" height="864" />
      </lowResolutions>
    </resolutions>
    <imageRatios>
      <imageRatio width="3" height="2" />
    </imageRatios>
    <ISOratings>
      <ISOrating>100</ISOrating>
      <ISOrating>200</ISOrating>
      <ISOrating>400</ISOrating>
      <ISOrating>800</ISOrating>
      <ISOrating>1600 (extended mode)</ISOrating>
      <ISOrating />
    </ISOratings>
    <sensorSize width="20.7" height="13.8" />
  </camera>
</cameras>
