=== disbeat/camera_info/IS-Projecto4/xml/summary.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="releasedDate" type="xs:date" />

  <xs:element name="manufacturer">
    <xs:complexType>
      <xs:all>
        <xs:element ref="totalCameras" />
        <xs:element ref="mostRecentCameras" />
        <xs:element ref="olderCameras" />
        <xs:element ref="resolutions" />
        <xs:element ref="modelsList" />
      </xs:all>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  
  <xs:element name="model" type="xs:string"/>

  <xs:element name="modelsList">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="model" maxOccurs="unbounded" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="maxResolutionCameras">
    <xs:complexType>
      <xs:sequence maxOccurs="1">
        <xs:element ref="resolution" />
        <xs:element ref="modelsList" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="minResolutionCameras">
    <xs:complexType>
      <xs:sequence maxOccurs="1">
        <xs:element ref="resolution" />
        <xs:element ref="modelsList" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="mostRecentCameras">
    <xs:complexType>
      <xs:sequence maxOccurs="1">
        <xs:element ref="releasedDate" />
        <xs:element ref="modelsList" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="olderCameras">
    <xs:complexType>
      <xs:sequence maxOccurs="1">
        <xs:element ref="releasedDate" />
        <xs:element ref="modelsList" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="resolution">
    <xs:complexType>
      <xs:attribute name="totalPixels" type="xs:integer" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="resolutions">
    <xs:complexType>
      <xs:sequence maxOccurs="1">
        <xs:element ref="minResolutionCameras" />
        <xs:element ref="maxResolutionCameras" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="summary">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="manufacturer" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="totalCameras" type="xs:integer" />

</xs:schema>

=== disbeat/camera_info/IS-Projecto4/xml/summary.xml
<?xml version="1.0" encoding="UTF-8"?>
<summary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="summary.xsd">
  <manufacturer name="Canon">
    <totalCameras>65</totalCameras>
    <mostRecentCameras>
      <releasedDate>2005-08-22</releasedDate>
      <modelsList>
        <model>Canon EOS 5D</model>
      </modelsList>
    </mostRecentCameras>
    <olderCameras>
      <releasedDate>2009-09-01</releasedDate>
      <modelsList>
        <model>Canon EOS 7D</model>
      </modelsList>
    </olderCameras>
    <resolutions>
      <minResolutionCameras>
        <resolution totalPixels="44800" />
        <modelsList>
          <model>Canon PowerShot SD970 IS (Digital IXUS 990 IS)</model>
          <model>Canon PowerShot A2100 IS</model>
          <model>Canon PowerShot D10</model>
          <model>Canon PowerShot SD960 IS (Digital IXUS 110 IS)</model>
          <model>Canon PowerShot SD780 IS (Digital IXUS 100 IS)</model>
          <model>Canon PowerShot SX200 IS</model>
          <model>Canon PowerShot A1100 IS</model>
        </modelsList>
      </minResolutionCameras>
      <maxResolutionCameras>
        <resolution totalPixels="21026304" />
        <modelsList>
          <model>Canon EOS 5D Mark II</model>
          <model>Canon EOS-1Ds Mark III</model>
        </modelsList>
      </maxResolutionCameras>
    </resolutions>
    <modelsList>
      <model>Canon EOS 7D</model>
      <model>Canon PowerShot SX20 IS</model>
      <model>Canon PowerShot SD980 IS (Digital IXUS 200 IS)</model>
      <model>Canon PowerShot SD940 IS (Digital IXUS 120 IS)</model>
      <model>Canon PowerShot SX120 IS</model>
      <model>Canon PowerShot S90</model>
      <model>Canon PowerShot G11</model>
      <model>Canon EOS 500D (EOS Rebel T1i, EOS Kiss Digital X3)</model>
      <model>Canon PowerShot SD970 IS (Digital IXUS 990 IS)</model>
      <model>Canon PowerShot A2100 IS</model>
      <model>Canon PowerShot D10</model>
      <model>Canon PowerShot SD960 IS (Digital IXUS 110 IS)</model>
      <model>Canon PowerShot SD1200 IS (Digital IXUS 95 IS)</model>
      <model>Canon PowerShot SD780 IS (Digital IXUS 100 IS)</model>
      <model>Canon PowerShot SX200 IS</model>
      <model>Canon PowerShot A1100 IS</model>
      <model>Canon PowerShot A480</model>
      <model>Canon EOS 5D Mark II</model>
      <model>Canon PowerShot G10</model>
      <model>Canon PowerShot SX1 IS</model>
      <model>Canon PowerShot SX10 IS</model>
      <model>Canon PowerShot SD880 IS (Digital IXUS 870 IS)</model>
      <model>Canon PowerShot SD990 IS (Digital IXUS 980 IS)</model>
      <model>Canon PowerShot E1</model>
      <model>Canon PowerShot SX110 IS</model>
      <model>Canon EOS 50D</model>
      <model>Canon PowerShot A1000 IS</model>
      <model>Canon PowerShot A2000 IS</model>
      <model>Canon EOS 1000D (EOS Digital Rebel XS)</model>
      <model>Canon PowerShot SD890 IS (Digital IXUS 970 IS, IXY Digital 820 IS)</model>
      <model>Canon PowerShot SD790 IS (Digital IXUS 90 IS)</model>
      <model>Canon PowerShot SD770 IS (Digital IXUS 85 IS)</model>
      <model>Canon PowerShot A580</model>
      <model>Canon PowerShot A590 IS</model>
      <model>Canon EOS 450D (EOS Digital Rebel XSi, EOS Kiss X2)</model>
      <model>Canon PowerShot A470</model>
      <model>Canon PowerShot SD1100 IS (Digital IXUS 80 IS)</model>
      <model>Canon EOS 40D</model>
      <model>Canon PowerShot SD870 IS (Digital IXUS 860 IS, IXY Digital 910 IS)</model>
      <model>Canon PowerShot G9</model>
      <model>Canon PowerShot SD950 IS (Digital IXUS 960 IS)</model>
      <model>Canon EOS-1Ds Mark III</model>
      <model>Canon PowerShot SX100 IS</model>
      <model>Canon PowerShot A720 IS</model>
      <model>Canon PowerShot A650 IS</model>
      <model>Canon PowerShot SD850 IS (Digital IXUS 950 IS, IXY Digital 810 IS)</model>
      <model>Canon PowerShot S5 IS</model>
      <model>Canon PowerShot SD1000 (Digital IXUS 70)</model>
      <model>Canon PowerShot TX1</model>
      <model>Canon EOS-1D Mark III</model>
      <model>Canon PowerShot SD750 (Digital IXUS 75)</model>
      <model>Canon PowerShot A560</model>
      <model>Canon PowerShot A570 IS</model>
      <model>Canon PowerShot A450</model>
      <model>Canon PowerShot A460</model>
      <model>Canon PowerShot A550</model>
      <model>Canon PowerShot SD900 (Digital IXUS 900 Ti)</model>
      <model>Canon PowerShot SD800 IS (Digital IXUS 850 IS, IXY Digital 900 IS)</model>
      <model>Canon PowerShot SD40 (Digital IXUS i7)</model>
      <model>Canon PowerShot G7</model>
      <model>Canon PowerShot A630</model>
      <model>Canon PowerShot A640</model>
      <model>Canon PowerShot A710 IS</model>
      <model>Canon EOS 400D (EOS Digital Rebel XTi, EOS Kiss Digital X)</model>
      <model>Canon EOS 5D</model>
    </modelsList>
  </manufacturer>
  <manufacturer name="Casio">
    <totalCameras>33</totalCameras>
    <mostRecentCameras>
      <releasedDate>2006-06-22</releasedDate>
      <modelsList>
        <model>Casio Exilim EX-Z70</model>
      </modelsList>
    </mostRecentCameras>
    <olderCameras>
      <releasedDate>2009-08-31</releasedDate>
      <modelsList>
        <model>Casio Exilim EX-Z33</model>
        <model>Casio Exilim EX-Z280</model>
      </modelsList>
    </olderCameras>
    <resolutions>
      <minResolutionCameras>
        <resolution totalPixels="307200" />
        <modelsList>
          <model>Casio Exilim EX-Z33</model>
          <model>Casio Exilim EX-Z280</model>
          <model>Casio Exilim EX-Z90</model>
          <model>Casio Exilim EX-H10</model>
          <model>Casio Exilim EX-Z29</model>
          <model>Casio Exilim EX-Z270</model>
          <model>Casio Exilim EX-S12</model>
          <model>Casio Exilim EX-S5</model>
          <model>Casio Exilim EX-FS10</model>
          <model>Casio Exilim EX-FC100</model>
          <model>Casio Exilim EX-Z400</model>
          <model>Casio Exilim EX-FH20</model>
          <model>Casio Exilim EX-Z300</model>
          <model>Casio Exilim EX-Z85</model>
          <model>Casio Exilim EX-Z250</model>
          <model>Casio Exilim EX-Z9</model>
          <model>Casio Exilim EX-Z80</model>
          <model>Casio Exilim EX-Z100</model>
          <model>Casio Exilim EX-S10</model>
          <model>Casio Exilim EX-Z200</model>
          <model>Casio Exilim Pro EX-F1</model>
          <model>Casio Exilim EX-Z1080</model>
          <model>Casio Exilim EX-V8</model>
          <model>Casio Exilim EX-Z77</model>
          <model>Casio Exilim EX-S880</model>
          <model>Casio Exilim EX-Z1200 SR</model>
          <model>Casio Exilim EX-Z75</model>
          <model>Casio Exilim EX-Z1050</model>
          <model>Casio Exilim EX-V7</model>
          <model>Casio Exilim EX-S770</model>
          <model>Casio Exilim EX-Z700</model>
          <model>Casio Exilim EX-S600d</model>
          <model>Casio Exilim EX-Z70</model>
        </modelsList>
      </minResolutionCameras>
      <maxResolutionCameras>
        <resolution totalPixels="12000000" />
        <modelsList>
          <model>Casio Exilim EX-Z280</model>
          <model>Casio Exilim EX-Z90</model>
          <model>Casio Exilim EX-H10</model>
          <model>Casio Exilim EX-S12</model>
          <model>Casio Exilim EX-Z400</model>
          <model>Casio Exilim EX-Z1200 SR</model>
        </modelsList>
      </maxResolutionCameras>
    </resolutions>
    <modelsList>
      <model>Casio Exilim EX-Z33</model>
      <model>Casio Exilim EX-Z280</model>
      <model>Casio Exilim EX-Z90</model>
      <model>Casio Exilim EX-H10</model>
      <model>Casio Exilim EX-Z29</model>
      <model>Casio Exilim EX-Z270</model>
      <model>Casio Exilim EX-S12</model>
      <model>Casio Exilim EX-S5</model>
      <model>Casio Exilim EX-FS10</model>
      <model>Casio Exilim EX-FC100</model>
      <model>Casio Exilim EX-Z400</model>
      <model>Casio Exilim EX-FH20</model>
      <model>Casio Exilim EX-Z300</model>
      <model>Casio Exilim EX-Z85</model>
      <model>Casio Exilim EX-Z250</model>
      <model>Casio Exilim EX-Z9</model>
      <model>Casio Exilim EX-Z80</model>
      <model>Casio Exilim EX-Z100</model>
      <model>Casio Exilim EX-S10</model>
      <model>Casio Exilim EX-Z200</model>
      <model>Casio Exilim Pro EX-F1</model>
      <model>Casio Exilim EX-Z1080</model>
      <model>Casio Exilim EX-V8</model>
      <model>Casio Exilim EX-Z77</model>
      <model>Casio Exilim EX-S880</model>
      <model>Casio Exilim EX-Z1200 SR</model>
      <model>Casio Exilim EX-Z75</model>
      <model>Casio Exilim EX-Z1050</model>
      <model>Casio Exilim EX-V7</model>
      <model>Casio Exilim EX-S770</model>
      <model>Casio Exilim EX-Z700</model>
      <model>Casio Exilim EX-S600d</model>
      <model>Casio Exilim EX-Z70</model>
    </modelsList>
  </manufacturer>
</summary>

=== disbeat/camera_info/IS-Projecto4/results/xmlResult7.xml
<?xml version="1.0" encoding="UTF-8"?>
<summary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="summary.xsd">
  <manufacturer name="olympus">
    <totalCameras>69</totalCameras>
    <mostRecentCameras>
      <releasedDate>2006-08-24</releasedDate>
      <modelsList>
        <model>Olympus FE-200</model>
        <model>Olympus FE-190</model>
        <model>Olympus Stylus 725 SW (mju 725 SW Digital)</model>
        <model>Olympus Stylus 730 (mju 730 Digital)</model>
        <model>Olympus Stylus 740 (mju 740 Digital)</model>
        <model>Olympus Stylus 750 (mju 750 Digital)</model>
        <model>Olympus FE-180</model>
        <model>Olympus FE-170</model>
        <model>Olympus Stylus 1000 (mju 1000 Digital)</model>
        <model>Olympus SP-510 UZ</model>
      </modelsList>
    </mostRecentCameras>
    <olderCameras>
      <releasedDate>2009-11-05</releasedDate>
      <modelsList>
        <model>Olympus PEN E-P2</model>
      </modelsList>
    </olderCameras>
    <resolutions>
      <minResolutionCameras>
        <resolution totalPixels="307200" />
        <modelsList>
          <model>Olympus PEN E-P2</model>
          <model>Olympus E-600</model>
          <model>Olympus Stylus 7010 (mju 7010)</model>
          <model>Olympus FE-5020 (X-935)</model>
          <model>Olympus FE-4000 (X-925)</model>
          <model>Olympus Stylus Tough 6010 (mju Tough 6010)</model>
          <model>Olympus PEN E-P1</model>
          <model>Olympus E-450</model>
          <model>Olympus E-620</model>
          <model>Olympus FE-5010</model>
          <model>Olympus FE-5000</model>
          <model>Olympus Stylus Tough 8000 (mju Tough 8000)</model>
          <model>Olympus Stylus 7000 (mju 7000)</model>
          <model>Olympus FE-3010</model>
          <model>Olympus Stylus 9000 (mju 9000)</model>
          <model>Olympus FE-3000</model>
          <model>Olympus FE-45</model>
          <model>Olympus Stylus Tough 6000 (mju Tough 6000)</model>
          <model>Olympus SP-590 UZ</model>
          <model>Olympus Stylus 550WP (mju  550WP)</model>
          <model>Olympus E-30</model>
          <model>Olympus SP-565UZ</model>
          <model>Olympus FE-20 (C-25, X-15)</model>
          <model>Olympus Stylus 1050 SW (mju 1050 SW)</model>
          <model>Olympus Stylus 1040 (mju 1040)</model>
          <model>Olympus FE-370</model>
          <model>Olympus FE-360 (C-570, X-875)</model>
          <model>Olympus E-520</model>
          <model>Olympus E-420</model>
          <model>Olympus Stylus 850 SW</model>
          <model>Olympus Stylus 840</model>
          <model>Olympus Stylus 1030 SW</model>
          <model>Olympus Stylus 1020</model>
          <model>Olympus FE-350</model>
          <model>Olympus FE-340 (C-560)</model>
          <model>Olympus FE-310</model>
          <model>Olympus SP-570 UZ</model>
          <model>Olympus Stylus 1010</model>
          <model>Olympus E-3</model>
          <model>Olympus FE-290</model>
          <model>Olympus FE-280</model>
          <model>Olympus FE-270</model>
          <model>Olympus SP-560 UZ</model>
          <model>Olympus Stylus 820 (mju 820 Digital)</model>
          <model>Olympus Stylus 790 SW (mju 790 SW Digital)</model>
          <model>Olympus FE-300</model>
          <model>Olympus Stylus 1200 (mju 1200 Digital)</model>
          <model>Olympus Stylus 830 (mju 830 Digital)</model>
          <model>Olympus E-410 (EVOLT E-410)</model>
          <model>Olympus E-510 (EVOLT E-510)</model>
          <model>Olympus Stylus 780 (mju 780 Digital)</model>
          <model>Olympus Stylus 760 (mju 760 Digital)</model>
          <model>Olympus SP-550 UZ</model>
          <model>Olympus Stylus 770 SW (mju 770 SW Digital)</model>
          <model>Olympus FE-250</model>
          <model>Olympus FE-240</model>
          <model>Olympus FE-230</model>
          <model>Olympus FE-210</model>
          <model>Olympus E-400</model>
          <model>Olympus FE-200</model>
          <model>Olympus FE-190</model>
          <model>Olympus Stylus 725 SW (mju 725 SW Digital)</model>
          <model>Olympus Stylus 730 (mju 730 Digital)</model>
          <model>Olympus Stylus 740 (mju 740 Digital)</model>
          <model>Olympus Stylus 750 (mju 750 Digital)</model>
          <model>Olympus FE-180</model>
          <model>Olympus FE-170</model>
          <model>Olympus Stylus 1000 (mju 1000 Digital)</model>
          <model>Olympus SP-510 UZ</model>
        </modelsList>
      </minResolutionCameras>
      <maxResolutionCameras>
        <resolution totalPixels="12192768" />
        <modelsList>
          <model>Olympus PEN E-P2</model>
          <model>Olympus E-600</model>
          <model>Olympus PEN E-P1</model>
          <model>Olympus E-620</model>
          <model>Olympus E-30</model>
        </modelsList>
      </maxResolutionCameras>
    </resolutions>
    <modelsList>
      <model>Olympus PEN E-P2</model>
      <model>Olympus E-600</model>
      <model>Olympus Stylus 7010 (mju 7010)</model>
      <model>Olympus FE-5020 (X-935)</model>
      <model>Olympus FE-4000 (X-925)</model>
      <model>Olympus Stylus Tough 6010 (mju Tough 6010)</model>
      <model>Olympus PEN E-P1</model>
      <model>Olympus E-450</model>
      <model>Olympus E-620</model>
      <model>Olympus FE-5010</model>
      <model>Olympus FE-5000</model>
      <model>Olympus Stylus Tough 8000 (mju Tough 8000)</model>
      <model>Olympus Stylus 7000 (mju 7000)</model>
      <model>Olympus FE-3010</model>
      <model>Olympus Stylus 9000 (mju 9000)</model>
      <model>Olympus FE-3000</model>
      <model>Olympus FE-45</model>
      <model>Olympus Stylus Tough 6000 (mju Tough 6000)</model>
      <model>Olympus SP-590 UZ</model>
      <model>Olympus Stylus 550WP (mju  550WP)</model>
      <model>Olympus E-30</model>
      <model>Olympus SP-565UZ</model>
      <model>Olympus FE-20 (C-25, X-15)</model>
      <model>Olympus Stylus 1050 SW (mju 1050 SW)</model>
      <model>Olympus Stylus 1040 (mju 1040)</model>
      <model>Olympus FE-370</model>
      <model>Olympus FE-360 (C-570, X-875)</model>
      <model>Olympus E-520</model>
      <model>Olympus E-420</model>
      <model>Olympus Stylus 850 SW</model>
      <model>Olympus Stylus 840</model>
      <model>Olympus Stylus 1030 SW</model>
      <model>Olympus Stylus 1020</model>
      <model>Olympus FE-350</model>
      <model>Olympus FE-340 (C-560)</model>
      <model>Olympus FE-310</model>
      <model>Olympus SP-570 UZ</model>
      <model>Olympus Stylus 1010</model>
      <model>Olympus E-3</model>
      <model>Olympus FE-290</model>
      <model>Olympus FE-280</model>
      <model>Olympus FE-270</model>
      <model>Olympus SP-560 UZ</model>
      <model>Olympus Stylus 820 (mju 820 Digital)</model>
      <model>Olympus Stylus 790 SW (mju 790 SW Digital)</model>
      <model>Olympus FE-300</model>
      <model>Olympus Stylus 1200 (mju 1200 Digital)</model>
      <model>Olympus Stylus 830 (mju 830 Digital)</model>
      <model>Olympus E-410 (EVOLT E-410)</model>
      <model>Olympus E-510 (EVOLT E-510)</model>
      <model>Olympus Stylus 780 (mju 780 Digital)</model>
      <model>Olympus Stylus 760 (mju 760 Digital)</model>
      <model>Olympus SP-550 UZ</model>
      <model>Olympus Stylus 770 SW (mju 770 SW Digital)</model>
      <model>Olympus FE-250</model>
      <model>Olympus FE-240</model>
      <model>Olympus FE-230</model>
      <model>Olympus FE-210</model>
      <model>Olympus E-400</model>
      <model>Olympus FE-200</model>
      <model>Olympus FE-190</model>
      <model>Olympus Stylus 725 SW (mju 725 SW Digital)</model>
      <model>Olympus Stylus 730 (mju 730 Digital)</model>
      <model>Olympus Stylus 740 (mju 740 Digital)</model>
      <model>Olympus Stylus 750 (mju 750 Digital)</model>
      <model>Olympus FE-180</model>
      <model>Olympus FE-170</model>
      <model>Olympus Stylus 1000 (mju 1000 Digital)</model>
      <model>Olympus SP-510 UZ</model>
    </modelsList>
  </manufacturer>
</summary>

=== disbeat/camera_info/IS-Projecto4/results/xmlResult-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<summary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="summary.xsd">
  <manufacturer name="canon">
    <totalCameras>66</totalCameras>
    <mostRecentCameras>
      <releasedDate>2005-08-22</releasedDate>
      <modelsList>
        <model>Canon EOS 5D</model>
      </modelsList>
    </mostRecentCameras>
    <olderCameras>
      <releasedDate>2009-10-20</releasedDate>
      <modelsList>
        <model>Canon EOS-1D Mark IV</model>
      </modelsList>
    </olderCameras>
    <resolutions>
      <minResolutionCameras>
        <resolution totalPixels="44800" />
        <modelsList>
          <model>Canon PowerShot D10</model>
          <model>Canon PowerShot SD970 IS (Digital IXUS 990 IS)</model>
          <model>Canon PowerShot A2100 IS</model>
          <model>Canon PowerShot SD960 IS (Digital IXUS 110 IS)</model>
          <model>Canon PowerShot SX200 IS</model>
          <model>Canon PowerShot SD780 IS (Digital IXUS 100 IS)</model>
          <model>Canon PowerShot A1100 IS</model>
        </modelsList>
      </minResolutionCameras>
      <maxResolutionCameras>
        <resolution totalPixels="21026304" />
        <modelsList>
          <model>Canon EOS 5D Mark II</model>
          <model>Canon EOS-1Ds Mark III</model>
        </modelsList>
      </maxResolutionCameras>
    </resolutions>
    <modelsList>
      <model>Canon EOS-1D Mark IV</model>
      <model>Canon EOS 7D</model>
      <model>Canon PowerShot SX120 IS</model>
      <model>Canon PowerShot SX20 IS</model>
      <model>Canon PowerShot SD980 IS (Digital IXUS 200 IS)</model>
      <model>Canon PowerShot SD940 IS (Digital IXUS 120 IS)</model>
      <model>Canon PowerShot S90</model>
      <model>Canon PowerShot G11</model>
      <model>Canon EOS 500D (EOS Rebel T1i, EOS Kiss Digital X3)</model>
      <model>Canon PowerShot SD1200 IS (Digital IXUS 95 IS)</model>
      <model>Canon PowerShot D10</model>
      <model>Canon PowerShot SD970 IS (Digital IXUS 990 IS)</model>
      <model>Canon PowerShot A2100 IS</model>
      <model>Canon PowerShot SD960 IS (Digital IXUS 110 IS)</model>
      <model>Canon PowerShot SX200 IS</model>
      <model>Canon PowerShot SD780 IS (Digital IXUS 100 IS)</model>
      <model>Canon PowerShot A1100 IS</model>
      <model>Canon PowerShot A480</model>
      <model>Canon PowerShot G10</model>
      <model>Canon EOS 5D Mark II</model>
      <model>Canon PowerShot SX1 IS</model>
      <model>Canon PowerShot SX10 IS</model>
      <model>Canon PowerShot SD880 IS (Digital IXUS 870 IS)</model>
      <model>Canon PowerShot SD990 IS (Digital IXUS 980 IS)</model>
      <model>Canon PowerShot SX110 IS</model>
      <model>Canon EOS 50D</model>
      <model>Canon PowerShot E1</model>
      <model>Canon PowerShot A1000 IS</model>
      <model>Canon PowerShot A2000 IS</model>
      <model>Canon EOS 1000D (EOS Digital Rebel XS)</model>
      <model>Canon PowerShot SD890 IS (Digital IXUS 970 IS, IXY Digital 820 IS)</model>
      <model>Canon PowerShot SD790 IS (Digital IXUS 90 IS)</model>
      <model>Canon PowerShot SD770 IS (Digital IXUS 85 IS)</model>
      <model>Canon PowerShot A580</model>
      <model>Canon PowerShot A590 IS</model>
      <model>Canon EOS 450D (EOS Digital Rebel XSi, EOS Kiss X2)</model>
      <model>Canon PowerShot SD1100 IS (Digital IXUS 80 IS)</model>
      <model>Canon PowerShot A470</model>
      <model>Canon PowerShot A720 IS</model>
      <model>Canon PowerShot SX100 IS</model>
      <model>Canon EOS-1Ds Mark III</model>
      <model>Canon PowerShot SD950 IS (Digital IXUS 960 IS)</model>
      <model>Canon PowerShot G9</model>
      <model>Canon PowerShot SD870 IS (Digital IXUS 860 IS, IXY Digital 910 IS)</model>
      <model>Canon PowerShot A650 IS</model>
      <model>Canon EOS 40D</model>
      <model>Canon PowerShot SD850 IS (Digital IXUS 950 IS, IXY Digital 810 IS)</model>
      <model>Canon PowerShot S5 IS</model>
      <model>Canon PowerShot SD750 (Digital IXUS 75)</model>
      <model>Canon PowerShot A560</model>
      <model>Canon PowerShot A570 IS</model>
      <model>Canon PowerShot SD1000 (Digital IXUS 70)</model>
      <model>Canon PowerShot TX1</model>
      <model>Canon EOS-1D Mark III</model>
      <model>Canon PowerShot A550</model>
      <model>Canon PowerShot A460</model>
      <model>Canon PowerShot A450</model>
      <model>Canon PowerShot SD800 IS (Digital IXUS 850 IS, IXY Digital 900 IS)</model>
      <model>Canon PowerShot SD40 (Digital IXUS i7, IXY Digital L4)</model>
      <model>Canon PowerShot G7</model>
      <model>Canon PowerShot SD900 (Digital IXUS 900 Ti)</model>
      <model>Canon PowerShot A710 IS</model>
      <model>Canon EOS 400D (EOS Digital Rebel XTi, EOS Kiss Digital X)</model>
      <model>Canon PowerShot A640</model>
      <model>Canon PowerShot A630</model>
      <model>Canon EOS 5D</model>
    </modelsList>
  </manufacturer>
</summary>
